name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build_linux_x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Configure Fractoid
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGOMP=ON

      - name: Build Fractoid
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/fractoid bin/fractoid_linux_x86-64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/fractoid_linux_x86-64

  build_linux_x86-64_openmp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Configure Fractoid
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Fractoid
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/fractoid bin/fractoid_linux_x86-64_openmp

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/fractoid_linux_x86-64_openmp

  build_windows_x86-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: pip install jinja2

      - name: Configure Fractoid
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Fractoid
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/fractoid.exe bin/fractoid_windows_x86-64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/fractoid_windows_x86-64.exe

  release:
    runs-on: ubuntu-latest
    needs: [build_linux_x86-64, build_linux_x86-64_openmp, build_windows_x86-64]

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Copy x86-64 Binaries to the Root Folder
        run: |
          cp artifact/fractoid_linux_x86-64 fractoid && cp artifact/fractoid_windows_x86-64.exe fractoid.exe

      - name: Create x86-64 Packages
        run: |
          zip -r fractoid_windows_x86-64.zip fractoid.exe example LICENSE.md
          tar -czf fractoid_linux_x86-64.tar.gz fractoid example LICENSE.md

      - name: Copy x86-64_openmp Binaries to the Root Folder
        run: |
          cp artifact/fractoid_linux_x86-64_openmp fractoid

      - name: Create x86-64_openmp Packages
        run: |
          tar -czf fractoid_linux_x86-64_openmp.tar.gz fractoid example LICENSE.md

      - name: Release linux_x86-64 Version of Fractoid
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: fractoid_linux_x86-64.tar.gz
          tag: ${{github.ref}}

      - name: Release linux_x86-64_openmp Version of Fractoid
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: fractoid_linux_x86-64_openmp.tar.gz
          tag: ${{github.ref}}

      - name: Release windows_x86-64 Version of Fractoid
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: fractoid_windows_x86-64.zip
          tag: ${{github.ref}}
